# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/tplots_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 750)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(700, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editdatafile = QtWidgets.QLineEdit(self.groupBox)
        self.editdatafile.setObjectName("editdatafile")
        self.horizontalLayout.addWidget(self.editdatafile)
        self.pbimport = QtWidgets.QPushButton(self.groupBox)
        self.pbimport.setObjectName("pbimport")
        self.horizontalLayout.addWidget(self.pbimport)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cbfileformat = QtWidgets.QComboBox(self.groupBox)
        self.cbfileformat.setMinimumSize(QtCore.QSize(120, 0))
        self.cbfileformat.setObjectName("cbfileformat")
        self.cbfileformat.addItem("")
        self.cbfileformat.addItem("")
        self.cbfileformat.addItem("")
        self.cbfileformat.addItem("")
        self.horizontalLayout_3.addWidget(self.cbfileformat)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.cbdelimiter = QtWidgets.QComboBox(self.groupBox)
        self.cbdelimiter.setMinimumSize(QtCore.QSize(120, 0))
        self.cbdelimiter.setObjectName("cbdelimiter")
        self.cbdelimiter.addItem("")
        self.cbdelimiter.addItem("")
        self.cbdelimiter.addItem("")
        self.horizontalLayout_3.addWidget(self.cbdelimiter)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.editdatacols = QtWidgets.QLineEdit(self.groupBox)
        self.editdatacols.setAlignment(QtCore.Qt.AlignCenter)
        self.editdatacols.setObjectName("editdatacols")
        self.horizontalLayout_3.addWidget(self.editdatacols)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setMinimumSize(QtCore.QSize(400, 320))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.treefigure = QtWidgets.QTreeWidget(self.groupBox_2)
        self.treefigure.setObjectName("treefigure")
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treefigure)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.gridLayout.addWidget(self.treefigure, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_3.setMinimumSize(QtCore.QSize(400, 280))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeplot = QtWidgets.QTreeWidget(self.groupBox_3)
        self.treeplot.setObjectName("treeplot")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeplot)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeplot)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeplot)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeplot)
        item_0.setCheckState(1, QtCore.Qt.Checked)
        item_0.setCheckState(2, QtCore.Qt.Unchecked)
        item_0.setCheckState(3, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Unchecked)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeplot)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0.setCheckState(2, QtCore.Qt.Unchecked)
        item_0.setCheckState(3, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Unchecked)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeplot)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0.setCheckState(2, QtCore.Qt.Unchecked)
        item_0.setCheckState(3, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.gridLayout_2.addWidget(self.treeplot, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.splitter)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbloaddata = QtWidgets.QPushButton(self.groupBox_4)
        self.pbloaddata.setMinimumSize(QtCore.QSize(0, 40))
        self.pbloaddata.setObjectName("pbloaddata")
        self.verticalLayout.addWidget(self.pbloaddata)
        self.pbdumptxt = QtWidgets.QPushButton(self.groupBox_4)
        self.pbdumptxt.setMinimumSize(QtCore.QSize(0, 40))
        self.pbdumptxt.setObjectName("pbdumptxt")
        self.verticalLayout.addWidget(self.pbdumptxt)
        self.pbdumpbin = QtWidgets.QPushButton(self.groupBox_4)
        self.pbdumpbin.setMinimumSize(QtCore.QSize(0, 40))
        self.pbdumpbin.setObjectName("pbdumpbin")
        self.verticalLayout.addWidget(self.pbdumpbin)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pbshowplots = QtWidgets.QPushButton(self.groupBox_6)
        self.pbshowplots.setMinimumSize(QtCore.QSize(0, 40))
        self.pbshowplots.setObjectName("pbshowplots")
        self.verticalLayout_4.addWidget(self.pbshowplots)
        self.pbcloseplots = QtWidgets.QPushButton(self.groupBox_6)
        self.pbcloseplots.setMinimumSize(QtCore.QSize(0, 40))
        self.pbcloseplots.setObjectName("pbcloseplots")
        self.verticalLayout_4.addWidget(self.pbcloseplots)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pbclearlog = QtWidgets.QPushButton(self.groupBox_5)
        self.pbclearlog.setObjectName("pbclearlog")
        self.horizontalLayout_2.addWidget(self.pbclearlog)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.listlog = QtWidgets.QListWidget(self.groupBox_5)
        self.listlog.setMinimumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listlog.setFont(font)
        self.listlog.setObjectName("listlog")
        self.verticalLayout_3.addWidget(self.listlog)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 37))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.menu_2.setFont(font)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.acaboutqt = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.acaboutqt.setFont(font)
        self.acaboutqt.setObjectName("acaboutqt")
        self.acabout = QtWidgets.QAction(MainWindow)
        self.acabout.setObjectName("acabout")
        self.acsave = QtWidgets.QAction(MainWindow)
        self.acsave.setObjectName("acsave")
        self.acopen = QtWidgets.QAction(MainWindow)
        self.acopen.setObjectName("acopen")
        self.acexit = QtWidgets.QAction(MainWindow)
        self.acexit.setObjectName("acexit")
        self.menu.addAction(self.acaboutqt)
        self.menu.addAction(self.acabout)
        self.menu_2.addAction(self.acopen)
        self.menu_2.addAction(self.acsave)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.acexit)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "tplots"))
        self.groupBox.setTitle(_translate("MainWindow", "数据描述"))
        self.label.setText(_translate("MainWindow", "数据文件路径"))
        self.pbimport.setText(_translate("MainWindow", "导入数据文件"))
        self.label_3.setText(_translate("MainWindow", "数据文件格式"))
        self.cbfileformat.setItemText(0, _translate("MainWindow", "文本"))
        self.cbfileformat.setItemText(1, _translate("MainWindow", "二进制 double"))
        self.cbfileformat.setItemText(2, _translate("MainWindow", "二进制 float"))
        self.cbfileformat.setItemText(3, _translate("MainWindow", "二进制 int"))
        self.label_5.setText(_translate("MainWindow", "分割字符"))
        self.cbdelimiter.setItemText(0, _translate("MainWindow", "空格"))
        self.cbdelimiter.setItemText(1, _translate("MainWindow", "逗号"))
        self.cbdelimiter.setItemText(2, _translate("MainWindow", "分号"))
        self.label_4.setText(_translate("MainWindow", "数据列数"))
        self.editdatacols.setText(_translate("MainWindow", "7"))
        self.groupBox_2.setTitle(_translate("MainWindow", "窗口属性"))
        self.treefigure.headerItem().setText(0, _translate("MainWindow", "属性"))
        self.treefigure.headerItem().setText(1, _translate("MainWindow", "值"))
        __sortingEnabled = self.treefigure.isSortingEnabled()
        self.treefigure.setSortingEnabled(False)
        self.treefigure.topLevelItem(0).setText(0, _translate("MainWindow", "窗口名称"))
        self.treefigure.topLevelItem(0).setText(1, _translate("MainWindow", "figure"))
        self.treefigure.topLevelItem(1).setText(0, _translate("MainWindow", "窗口大小"))
        self.treefigure.topLevelItem(2).setText(0, _translate("MainWindow", "横轴数据"))
        self.treefigure.topLevelItem(2).setText(1, _translate("MainWindow", "指定数据列 [0]"))
        self.treefigure.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "指定数据列"))
        self.treefigure.topLevelItem(2).child(0).setText(1, _translate("MainWindow", "0"))
        self.treefigure.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "计数索引"))
        self.treefigure.topLevelItem(3).setText(0, _translate("MainWindow", "标题"))
        self.treefigure.topLevelItem(3).setText(1, _translate("MainWindow", "title"))
        self.treefigure.topLevelItem(4).setText(0, _translate("MainWindow", "横轴标签"))
        self.treefigure.topLevelItem(4).setText(1, _translate("MainWindow", "xlabel"))
        self.treefigure.topLevelItem(5).setText(0, _translate("MainWindow", "纵轴标签"))
        self.treefigure.topLevelItem(5).setText(1, _translate("MainWindow", "ylabel"))
        self.treefigure.topLevelItem(6).setText(0, _translate("MainWindow", "字体大小"))
        self.treefigure.topLevelItem(6).setText(1, _translate("MainWindow", "20"))
        self.treefigure.topLevelItem(7).setText(0, _translate("MainWindow", "显示栅格"))
        self.treefigure.topLevelItem(8).setText(0, _translate("MainWindow", "显示图例"))
        self.treefigure.topLevelItem(8).child(0).setText(0, _translate("MainWindow", "标记和曲线"))
        self.treefigure.topLevelItem(8).child(1).setText(0, _translate("MainWindow", "标记"))
        self.treefigure.topLevelItem(8).child(2).setText(0, _translate("MainWindow", "图例位置"))
        self.treefigure.topLevelItem(9).setText(0, _translate("MainWindow", "跳过行数"))
        self.treefigure.topLevelItem(9).setText(1, _translate("MainWindow", "0"))
        self.treefigure.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("MainWindow", "绘图属性"))
        self.treeplot.headerItem().setText(0, _translate("MainWindow", "属性"))
        self.treeplot.headerItem().setText(1, _translate("MainWindow", "X"))
        self.treeplot.headerItem().setText(2, _translate("MainWindow", "Y"))
        self.treeplot.headerItem().setText(3, _translate("MainWindow", "Z"))
        __sortingEnabled = self.treeplot.isSortingEnabled()
        self.treeplot.setSortingEnabled(False)
        self.treeplot.topLevelItem(0).setText(0, _translate("MainWindow", "分组显示"))
        self.treeplot.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "初始索引"))
        self.treeplot.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "1"))
        self.treeplot.topLevelItem(1).setText(0, _translate("MainWindow", "数据列号"))
        self.treeplot.topLevelItem(1).setText(1, _translate("MainWindow", "1"))
        self.treeplot.topLevelItem(1).setText(2, _translate("MainWindow", "2"))
        self.treeplot.topLevelItem(1).setText(3, _translate("MainWindow", "3"))
        self.treeplot.topLevelItem(2).setText(0, _translate("MainWindow", "图例名称"))
        self.treeplot.topLevelItem(2).setText(1, _translate("MainWindow", "X"))
        self.treeplot.topLevelItem(2).setText(2, _translate("MainWindow", "Y"))
        self.treeplot.topLevelItem(2).setText(3, _translate("MainWindow", "Z"))
        self.treeplot.topLevelItem(3).setText(0, _translate("MainWindow", "绘制曲线"))
        self.treeplot.topLevelItem(3).setText(1, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(3).setText(2, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(3).setText(3, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "样式类型"))
        self.treeplot.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "曲线宽度"))
        self.treeplot.topLevelItem(3).child(1).setText(1, _translate("MainWindow", "1.5"))
        self.treeplot.topLevelItem(3).child(1).setText(2, _translate("MainWindow", "1.5"))
        self.treeplot.topLevelItem(3).child(1).setText(3, _translate("MainWindow", "1.5"))
        self.treeplot.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "曲线颜色"))
        self.treeplot.topLevelItem(3).child(2).setText(1, _translate("MainWindow", "自定义"))
        self.treeplot.topLevelItem(3).child(2).child(0).setText(0, _translate("MainWindow", "自定义"))
        self.treeplot.topLevelItem(3).child(2).child(0).setText(1, _translate("MainWindow", "y"))
        self.treeplot.topLevelItem(3).child(2).child(0).setText(2, _translate("MainWindow", "y"))
        self.treeplot.topLevelItem(3).child(2).child(0).setText(3, _translate("MainWindow", "y"))
        self.treeplot.topLevelItem(4).setText(0, _translate("MainWindow", "特殊标记"))
        self.treeplot.topLevelItem(4).setText(1, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(4).setText(2, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(4).setText(3, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "标记类型"))
        self.treeplot.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "标记大小"))
        self.treeplot.topLevelItem(4).child(1).setText(1, _translate("MainWindow", "6"))
        self.treeplot.topLevelItem(4).child(1).setText(2, _translate("MainWindow", "6"))
        self.treeplot.topLevelItem(4).child(1).setText(3, _translate("MainWindow", "6"))
        self.treeplot.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "标记颜色"))
        self.treeplot.topLevelItem(4).child(2).setText(1, _translate("MainWindow", "自定义"))
        self.treeplot.topLevelItem(4).child(2).child(0).setText(0, _translate("MainWindow", "自定义"))
        self.treeplot.topLevelItem(4).child(2).child(0).setText(1, _translate("MainWindow", "b"))
        self.treeplot.topLevelItem(4).child(2).child(0).setText(2, _translate("MainWindow", "green"))
        self.treeplot.topLevelItem(4).child(2).child(0).setText(3, _translate("MainWindow", "#0000FF"))
        self.treeplot.topLevelItem(5).setText(0, _translate("MainWindow", "嵌入文本"))
        self.treeplot.topLevelItem(5).setText(1, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(5).setText(2, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(5).setText(3, _translate("MainWindow", "添加"))
        self.treeplot.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "文本内容"))
        self.treeplot.topLevelItem(5).child(0).setText(1, _translate("MainWindow", "text"))
        self.treeplot.topLevelItem(5).child(0).setText(2, _translate("MainWindow", "$x^2$"))
        self.treeplot.topLevelItem(5).child(0).setText(3, _translate("MainWindow", "text [$\\sigma$]"))
        self.treeplot.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "显示坐标"))
        self.treeplot.topLevelItem(5).child(1).setText(1, _translate("MainWindow", "[0, 0]"))
        self.treeplot.topLevelItem(5).child(1).setText(2, _translate("MainWindow", "[0, 0]"))
        self.treeplot.topLevelItem(5).child(1).setText(3, _translate("MainWindow", "[0, 0]"))
        self.treeplot.topLevelItem(5).child(1).child(0).setText(0, _translate("MainWindow", "X"))
        self.treeplot.topLevelItem(5).child(1).child(0).setText(1, _translate("MainWindow", "0"))
        self.treeplot.topLevelItem(5).child(1).child(0).setText(2, _translate("MainWindow", "0"))
        self.treeplot.topLevelItem(5).child(1).child(0).setText(3, _translate("MainWindow", "0"))
        self.treeplot.topLevelItem(5).child(1).child(1).setText(0, _translate("MainWindow", "Y"))
        self.treeplot.topLevelItem(5).child(1).child(1).setText(1, _translate("MainWindow", "0"))
        self.treeplot.topLevelItem(5).child(1).child(1).setText(2, _translate("MainWindow", "0"))
        self.treeplot.topLevelItem(5).child(1).child(1).setText(3, _translate("MainWindow", "0"))
        self.treeplot.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "字体大小"))
        self.treeplot.topLevelItem(5).child(2).setText(1, _translate("MainWindow", "20"))
        self.treeplot.topLevelItem(5).child(2).setText(2, _translate("MainWindow", "20"))
        self.treeplot.topLevelItem(5).child(2).setText(3, _translate("MainWindow", "20"))
        self.treeplot.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "字体颜色"))
        self.treeplot.topLevelItem(5).child(3).setText(1, _translate("MainWindow", "k"))
        self.treeplot.topLevelItem(5).child(3).setText(2, _translate("MainWindow", "k"))
        self.treeplot.topLevelItem(5).child(3).setText(3, _translate("MainWindow", "k"))
        self.treeplot.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("MainWindow", "数据"))
        self.pbloaddata.setText(_translate("MainWindow", "加载数据"))
        self.pbdumptxt.setText(_translate("MainWindow", "导出为文本"))
        self.pbdumpbin.setText(_translate("MainWindow", "导出为二进制double"))
        self.groupBox_6.setTitle(_translate("MainWindow", "绘图"))
        self.pbshowplots.setText(_translate("MainWindow", "显示绘图"))
        self.pbcloseplots.setText(_translate("MainWindow", "关闭绘图"))
        self.groupBox_5.setTitle(_translate("MainWindow", "操作日志"))
        self.pbclearlog.setText(_translate("MainWindow", "清除日志"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.menu_2.setTitle(_translate("MainWindow", "文件"))
        self.acaboutqt.setText(_translate("MainWindow", "关于Qt"))
        self.acabout.setText(_translate("MainWindow", "关于tplots"))
        self.acsave.setText(_translate("MainWindow", "保存配置"))
        self.acopen.setText(_translate("MainWindow", "打开配置"))
        self.acexit.setText(_translate("MainWindow", "退出"))
